name: Stable Songster build
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build and upload Songster
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'macos-12'
            version: '14.2'

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter SDK
        uses: MobileDevOps/flutter-sdk-action@v1.0.0
        with:
          flutter-sdk-version: 3.24.1

      - name: Compile Flutter app
        run: FLUTTER_ENV="${{ secrets.FLUTTER_ENV }}" VERSION="{{ github.ref_name }}" make compile

      - name: Convert to IPA
        run: make ipa

      - name: Get current date
        id: date
        run: echo "date=$(date -u +'%c')" >> $GITHUB_OUTPUT

      - name: Get current date in SideStore date form
        id: date_altstore
        run: echo "date=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Upload to new stable release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.PAT_GITHUB }}
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false

          files: songster.ipa
          body: |
            ## Changelog
            
            - TODO
            
            ## Build Info
            
            Built at (UTC): `${{ steps.date.outputs.date }}`
            Built at (UTC date): `${{ steps.date_altstore.outputs.date }}`
            Commit SHA: `${{ github.sha }}`
            Version: `${{ github.ref_name }}`

      - name: Upload SideStore.ipa Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: songster.ipa
          path: songster.ipa

      - name: Reset SideSource cache
        run: curl $SIDESOURCE_RESETCACHE_URL
        env:
          SIDESOURCE_RESETCACHE_URL: ${{ secrets.SIDESOURCE_RESETCACHE_URL }} 

